"""
create_pytorch_data.py — Build PyTorch Geometric datasets for AEV-PLIG-Coulomb-DDD.

Differences from create_pytorch_data.py:
  - Reads graphs_ddd.pickle (generated by generate_graphs_ddd.py)
  - Z-score normalises coulomb_energy using training-split statistics
  - Saves normalisation stats to processed_ddd/coulomb_norm_stats.json
  - Writes .pt files to data/processed_ddd/ via GraphDataset_DDD
"""

import pandas as pd
import pickle
import json
import os
import argparse
import numpy as np

from utils import GraphDataset_DDD
from config import DATASET_CSV


def main():
    parser = argparse.ArgumentParser(
        description="Create PyTorch Geometric datasets for qAEV-PLIG-2"
    )
    parser.add_argument("--graphs", type=str, default="data/graphs_ddd.pickle",
                        help="Path to DDD graphs pickle")
    parser.add_argument("--csv", type=str, default=DATASET_CSV,
                        help="Path to dataset CSV")
    parser.add_argument("--dataset_name", type=str, default="qaev_plig_2",
                        help="Dataset name prefix for output files")
    parser.add_argument("--processed_dir", type=str, default="data/processed_ddd",
                        help="Directory for normalisation stats JSON")
    args = parser.parse_args()

    # ── Load graphs ──────────────────────────────────────────────────────────
    print(f"Loading graphs from {args.graphs}")
    with open(args.graphs, 'rb') as handle:
        graphs_dict = pickle.load(handle)
    print(f"Loaded {len(graphs_dict)} graphs")

    # ── Load dataset CSV ─────────────────────────────────────────────────────
    data = pd.read_csv(args.csv)
    print(data[['split']].value_counts())

    available = set(graphs_dict.keys())
    before = len(data)
    data = data[data['unique_id'].isin(available)]
    if len(data) < before:
        print(f"Warning: {before - len(data)} complexes in CSV have no graph, skipped")

    # ── Compute Coulomb normalisation stats from training split ──────────────
    train_df = data[data['split'] == 'train']
    train_ec_values = np.array([
        graphs_dict[uid][4] for uid in train_df['unique_id'] if uid in graphs_dict
    ])

    os.makedirs(args.processed_dir, exist_ok=True)

    if len(train_ec_values) > 1:
        ec_mean = float(train_ec_values.mean())
        ec_std  = float(train_ec_values.std())
        if ec_std < 1e-8:
            ec_std = 1.0
    elif len(train_ec_values) == 1:
        # Single-element set: z-score is 0 by convention; std set to 1
        ec_mean = float(train_ec_values[0])
        ec_std  = 1.0
    else:
        raise RuntimeError("No training complexes found — cannot compute normalisation stats")

    norm_stats = {"ec_mean": ec_mean, "ec_std": ec_std}
    stats_path = os.path.join(args.processed_dir, "coulomb_norm_stats.json")
    with open(stats_path, 'w') as f:
        json.dump(norm_stats, f, indent=2)
    print(f"Coulomb norm stats: mean={ec_mean:.3f}, std={ec_std:.3f}  →  {stats_path}")

    # ── Apply z-score normalisation to ALL splits ────────────────────────────
    normalised_graphs = {}
    for uid, graph in graphs_dict.items():
        c_size, features, edge_index, edge_attr, raw_ec = graph
        normalised_ec = (raw_ec - ec_mean) / ec_std
        normalised_graphs[uid] = (c_size, features, edge_index, edge_attr, normalised_ec)

    # ── Build PyTorch Geometric .pt files ────────────────────────────────────
    dataset = args.dataset_name

    for split in ['train', 'valid', 'test']:
        df = data[data['split'] == split]
        if len(df) == 0:
            print(f"No {split} data, skipping")
            continue
        ids = list(df['unique_id'])
        y   = list(df['pK'])
        print(f'Preparing {dataset}_{split}.pt ({len(ids)} samples)')

        if split == 'train':
            train_data = GraphDataset_DDD(
                root='data', dataset=dataset + '_' + split,
                ids=ids, y=y, graphs_dict=normalised_graphs,
            )
            y_scaler = train_data.y_scaler
        else:
            GraphDataset_DDD(
                root='data', dataset=dataset + '_' + split,
                ids=ids, y=y, graphs_dict=normalised_graphs,
                y_scaler=y_scaler,
            )

    print("Done.")


if __name__ == "__main__":
    main()
